version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: django_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_web
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate --noinput &&
             gunicorn nowplay_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      # - media_volume:/app/media

  caddy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  # media_volume:
  caddy_data:
  caddy_config:
