# Generated by Django 6.0.3 on 2026-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('student', 'Student'), ('admin', 'Admin')], default='free', max_length=10),
        ),
    ]
