# Generated by Django 6.0.3 on 2026-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_album_cover_artist_avatar_track_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Podcast', 'Podcast'), ('Education', 'Education'), ('Radio', 'Radio'), ('Ugandan Music', 'Ugandan Music'), ('Audiobooks', 'Audiobooks'), ('Poems', 'Poems'), ('Audio Plays', 'Audio Plays')], max_length=20),
        ),
    ]
