# Generated by Django 6.0.3 on 2026-05-16 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_track_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='creator_type',
            field=models.CharField(choices=[('artist', 'Musical Artist'), ('host', 'Podcast Host'), ('author', 'Author'), ('poet', 'Poet'), ('director', 'Director')], default='artist', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('narrator', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='audiobook_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(limit_choices_to={'creator_type': 'author'}, on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks', to='core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='AudioBookChapter',
            fields=[
                ('track_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.track')),
                ('chapter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.audiobook')),
            ],
            options={
                'verbose_name': 'Audiobook Chapter',
            },
            bases=('core.track',),
        ),
        migrations.CreateModel(
            name='AudioPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cast', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='audioplay_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(limit_choices_to={'creator_type': 'director'}, on_delete=django.db.models.deletion.CASCADE, related_name='audio_plays', to='core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='AudioPlayAct',
            fields=[
                ('track_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.track')),
                ('act_number', models.PositiveIntegerField(blank=True, null=True)),
                ('play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='core.audioplay')),
            ],
            bases=('core.track',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='podcast_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(limit_choices_to={'creator_type': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('track_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.track')),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('podcast_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.podcast')),
            ],
            options={
                'verbose_name': 'Podcast Episode',
            },
            bases=('core.track',),
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('track_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.track')),
                ('poet', models.ForeignKey(blank=True, limit_choices_to={'creator_type': 'poet'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_poems', to='core.artist')),
            ],
            bases=('core.track',),
        ),
    ]
