name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Get code
      - name: Checkout
        uses: actions/checkout@v4

      # Build & push image
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yourdockerhubusername/nowplay:latest

      # Deploy to VPS
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            cd ~/NowPlay_Backend

            docker pull yourdockerhubusername/nowplay:latest

            docker-compose down
            docker-compose up -d

            docker system prune -f
