name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CBM

    steps:
      # 1. Get code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Deploy to VPS via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            cd ~/NowPlay_Backend

            # Pull latest code from your repo
            git pull origin main

            # Rebuild containers locally (NO docker hub)
            docker-compose down
            docker-compose up -d --build

            # Clean unused images/containers
            docker system prune -f
